### ISSUE TITLE
non forgetful inheritance detected

### ISSUE THREAD

**Issue by affeldt-aist** [affeldt-aist/monae#97]
https://github.com/affeldt-aist/monae/blob/30808b48408d53400db48ade7f366a8340a99d06/category.v#L906-L907

https://github.com/affeldt-aist/monae/blob/30808b48408d53400db48ade7f366a8340a99d06/category.v#L959-L961

@t6s

**Comment by hivert** [comment]
See https://github.com/affeldt-aist/monae/pull/143 for a fix.
